apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gateway-envoy
  namespace: istio-system
  labels:
    release: crypto
spec:
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      istio: ingressgateway
  podMetricsEndpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 10s