apiVersion: v2
name: crypto-istio
description: Chart to install istio
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies: 
  - name: istiod
    version: "1.28.0"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
  - name: base
    alias: istio-base
    version: "1.28.0"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
  - name: gateway
    alias: istio-gateway
    version: "1.28.0"
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
