istio:
  enabled: true
  namespace:
    create: true

istio-gateway:
  name: istio-ingressgateway

istiod:
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
    extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.default.svc.cluster.local
        resource_detectors:
          environment: {}

namespace:
  create: true