apiVersion: v2
name: bitcoin-price
description: Chart to install crypto-price app and it's observability
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: kube-prometheus-stack
    version: 79.5.0
    repository: https://prometheus-community.github.io/helm-charts
  # - name: karpenter
  #   version: "1.8.x"
  #   repository: "public.ecr.aws/karpenter"
  #   condition: karpenter.enabled
  - name: opentelemetry-collector
    version: "0.139.0"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: jaeger
    version: "3.4.1"
    repository: https://jaegertracing.github.io/helm-charts
  - name: jenkins
    version: "5.8.110"
    repository: https://charts.jenkins.io
