{{- if .Values.karpenter.enabled }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: crypto-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        name: crypto-nodeclass

      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand", "spot"]

        - key: node.kubernetes.io/instance-type
          operator: Exists

        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]

        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
    budgets:
      - nodes: "10%"

  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
{{- end }}