{{- if .Values.karpenter.enabled }}
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: crypto-nodeclass
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: crypto-cluster

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: crypto-cluster

  amiFamily: AL2023

  role: "crypto-role"

  tags:
    karpenter.sh/discovery: crypto-cluster
    Name: karpenter-node
{{- end }}