{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default "test-crypto-price"}}
  labels:
    app: {{ .Values.namespace.appLabel | default "crypto-price-app" }}
{{- end }}