apiVersion: karpenter.sh/v1beta1
kind: Provisioner
metadata:
  name: crypto-karpenter-provisioner
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand", "spot"]

    - key: node.kubernetes.io/instance-type
      operator: Exists

    - key: kubernetes.io/arch
      operator: In
      values: ["amd64", "arm64"]

    - key: kubernetes.io/os
      operator: In
      values: ["linux"]

  consolidation:
    enabled: true

  deprovisioning:
    enabled: true

  nodeClassRef:
    name: crypto-nodeclass
  
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi