apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crypto-price-monitor
  namespace: {{ .Values.namespace.name }}
  labels:
    release: {{ $.Release.Name | quote }}
spec:
  selector:
    matchLabels:
      {{- include "bitcoin-price.labels" . | nindent 6 }}
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 5s